const DB_NAME="education_platform_files_v1", STORE="files", CACHE=new Map();
const openDb=()=>new Promise((resolve,reject)=>{const r=indexedDB.open(DB_NAME,1);r.onupgradeneeded=()=>{if(!r.result.objectStoreNames.contains(STORE))r.result.createObjectStore(STORE,{keyPath:"id"})};r.onsuccess=()=>resolve(r.result);r.onerror=()=>reject(r.error||Error("تعذر فتح مساحة الملفات المحلية."))});
const id=()=>`${Date.now().toString(36)}-${crypto.randomUUID?.()||Math.random().toString(36).slice(2)}`;
export const isLocalFileUrl=v=>typeof v==="string"&&v.startsWith("local-file://");
export async function saveLocalFile(file,{folder="files",signal,onProgress}={}){if(!(file instanceof Blob))throw Error("الملف غير صالح.");if(signal?.aborted)throw Object.assign(Error("تم الإلغاء."),{code:"upload-canceled"});const fileId=id(),record={id:fileId,folder,blob:file,name:file.name||"file",size:file.size||0,type:file.type||"application/octet-stream",createdAt:Date.now()};onProgress?.(Math.round(file.size*.1));const db=await openDb();try{await new Promise((resolve,reject)=>{const tx=db.transaction(STORE,"readwrite");tx.objectStore(STORE).put(record);tx.oncomplete=resolve;tx.onerror=()=>reject(tx.error||Error("تعذر حفظ الملف."));tx.onabort=()=>reject(Object.assign(Error("تم الإلغاء."),{code:"upload-canceled"}));if(signal)signal.addEventListener("abort",()=>{try{tx.abort()}catch{}},{once:true})})}finally{db.close()}if(signal?.aborted)throw Object.assign(Error("تم الإلغاء."),{code:"upload-canceled"});onProgress?.(file.size);return{file_url:`local-file://${fileId}`,path:`indexeddb/${fileId}`,file_id:fileId,name:record.name,size:record.size,type:record.type,provider:"browser-indexeddb"}}
export async function getLocalFileRecord(v){if(!isLocalFileUrl(v))return null;const db=await openDb();try{return await new Promise((resolve,reject)=>{const r=db.transaction(STORE,"readonly").objectStore(STORE).get(v.slice(13));r.onsuccess=()=>resolve(r.result||null);r.onerror=()=>reject(r.error)})}finally{db.close()}}
export async function resolveFileUrl(v){if(!v||!isLocalFileUrl(v))return v||"";if(CACHE.has(v))return CACHE.get(v);const r=await getLocalFileRecord(v);if(!r?.blob)throw Error("الملف غير موجود على هذا الجهاز.");const u=URL.createObjectURL(r.blob);CACHE.set(v,u);return u}
export async function openLocalFile(v,{download=false}={}){const r=await getLocalFileRecord(v);if(!r?.blob)throw Error("الملف غير موجود على هذا الجهاز.");const u=URL.createObjectURL(r.blob);if(download){const a=document.createElement("a");a.href=u;a.download=r.name||"download";document.body.appendChild(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(u),1000)}else{const w=window.open(u,"_blank","noopener,noreferrer");if(!w)window.location.assign(u);setTimeout(()=>URL.revokeObjectURL(u),60000)}return r}
export function revokeResolvedFileUrl(v){const u=CACHE.get(v);if(u){URL.revokeObjectURL(u);CACHE.delete(v)}}
